/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/ui/button/Button.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IIconoirHomeSimpleDoor: typeof import('~icons/iconoir/home-simple-door')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
